--Create DESIGNATION Table
DECLARE nCount NUMBER;

BEGIN
SELECT count(*) into nCount FROM user_tables where table_name = 'DESIGNATION';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('TABLE DESIGNATION ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE DESIGNATION(
     DESIGNATION_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
     NAME                  VARCHAR(16) UNIQUE NOT NULL,
     PRIMARY KEY(DESIGNATION_ID))';    
END IF;

--Create LOAN Table
SELECT count(*) into nCount FROM user_tables where table_name = 'LOAN';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('LOAN PEOPLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE LOAN(
      LOAN_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY,
      TYPE          VARCHAR(20) NOT NULL,
      AMOUNT        NUMBER(20)  NOT NULL,
      ROI           FLOAT(15)   NOT NULL,
      DURATION      FLOAT(15),    
      PRIMARY KEY(LOAN_ID))';  
END IF;

--Create CARD_SERVICES Table
SELECT count(*) into nCount FROM user_tables where table_name = 'CARD_SERVICES';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('CARD_SERVICES PEOPLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE CARD_SERVICES(
      CARD_SERVICES_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY,
      TYPE                    VARCHAR(20) UNIQUE NOT NULL,
      CARD_NUMBER             NUMBER(20)  UNIQUE NOT NULL,
      VALID_THROUGH           VARCHAR(15) NOT NULL,
      CVV                     NUMBER(15),
      CHECK(REGEXP_LIKE(CARD_NUMBER,''^[0-9]{16}$'')),
      CHECK(REGEXP_LIKE(VALID_THROUGH,''^((0[1-9])|(1[0-2]))\/(\d{4})$'')),
      CHECK(REGEXP_LIKE(CVV,''^[0-9]{3}$'')),
      PRIMARY KEY(CARD_SERVICES_ID))';  
END IF;

--Create ADDRESS Table
SELECT count(*) into nCount FROM user_tables where table_name = 'ADDRESS';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('ADDRESS PEOPLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE 'CREATE TABLE ADDRESS(
      ADDRESS_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY,
      ADDRESSLINE            VARCHAR(20) NOT NULL,
      CITY                   VARCHAR(15) NOT NULL,
      STATE                  NUMBER(15)  NOT NULL,    
      COUNTRY                VARCHAR(20) NOT NULL,
      ZIP_CODE               NUMBER(6) NOT NULL,
      CHECK(REGEXP_LIKE(ZIP_CODE,''^[0-9]{5}$'')),
      PRIMARY KEY(ADDRESS_ID))';  
END IF;
END;


select * from DESIGNATION;
select * from LOAN;
select * from CARD_SERVICES
select * from ADDRESS;